language: node_js
node_js:
- '6.9'
script:
- npm run lint
- npm test
- npm run build
deploy:
  provider: npm
  email: jason@jasons.io
  skip_cleanup: true
  api_key:
    secure: Bna2H+nCmUq5F/MX51fzm1F/58LCyFIF8IHUs05EftLIE9foGP0ueEt1OoNyzRXaxb+9/5oPaEeqTMpkq1+uDDyF2TrheMyhgj+EMI23skA6OnDyQ5Nj/DwPIziIQtNZDC3p9FyivJPNBLm3GAMiX8BwVCtdkNRziVwqtyeaVzP9JDmxDQjqwPMZSalx2SQepsuXD48UyhLG0NeMul6UuuBqSxk+ekaTG2m3iOXzE33RTFdLGWz1z8QsU/DdvcDeOL5V30YwTOb0Y88QJUqOtLYKeJGgBB3Wse1NZszg5LoCJWEdWSXs5XJMddk/C+6ACgkH99PyLwMWVRuqnagJaWRbhWLkWSZRK/iGqhZA6jGc0KQ/cO5ii+QuzoF983BiMPiq1bLsz9A7T+CNUIjVTvAJS68Hf1BrmSwuvMqkNqXAf2amypWM7ovnlHnKHdttYFivvfY+4de/r6IHYmsBRe7MmKIaI0w9nWP8nLwZsov36vn3a1TGO9+QDXCvav2/k2WtiCoOb23RbVTwyC9tnl9RrSJtTwylo+XBYBrzWd5J0rTkQUDCRyGKJ4N/sBchboB4XwU3SMA+G2AZCCw/mrnV7haYDHQubgMd3s+ecMJ9/PbXtlPePLoNoRTYIR5uGNlS7tiEOMprWPWeIwUYnwUt0YTiagzSGtG5P0Jgljs=
  on:
    tags: true
    repo: strothj/pomoapp-frontend
    branch: master
