language: node_js
node_js:
- '6.9'
- node
scripts:
- npm run lint
- npm test
after_success:
- build/deploy.sh
env:
  global:
  - secure: Xq1z2uIXFi/2YmeXhaBy4T2Owrxw5wJWJ/+Tu5dENHd+aPpwIATCoWHMFsxYAOG5pdUel/vwOljkEfxSP47F7YJ28LpqMjEXE23G0mjwrGzX9AEvjoPwfxzmwboTXt56w3ltfu6UCd8s5QDFtTY+sZE7yecnmjtfn+dXuhM/k27ePpUh6n0zRdZwW8vChi4QXimsSZIKI/1Ef+0XZOQG/lAxnJ9vu8ftjFYSFSJENMn9oF926WclRS82ev62OlggIytN45zN1cCbOxm9RjiTZdFNLTsus5xFptCKwB+25Kptq050Q5WAOyQF2jLeMD4hXHH2ddlHRId1AljgGFBV79F+bsFHt/NVVL3EZFqRe/EMBVMCrJStEgLON+G9m4b6yDYRR9VrFkuDFyCM2oOmK/+mJ60oEwtL4r6PiDq63Meyz+7NYNmgyRK3PeB8EKcP+zmanTwLHewhY9yrfmFJt50aOOoSK0pBga4kGkNIiFftM5o1//EcdS75fSwf+a4Fojx+UrpgTfU2U7AGF/r2z6gAtSTr4EI1qjLZMJWAFZcdIwPWEhuZhhKwF4Vv394W5Vnf9/OtcRWE+GJsZcGi8FLpRPwdIOD6jjkBsa5myeaoTaeDIzhVw0sjz86m8N4/MfSwh1DwfLv4Kp74mCDTG6n5A8H/u9o3VaQwQ8iCZ8o=
  - secure: ehZqUsx0kjg6p1MPwUIDj8SirTnxpsczMt4I+Fkmv7xT3WNSmA7PBtGlydPkzI3lpViNKlbjr9U8/+aFgN595AFGx+j+BXW1Wxt5GF67dy9QXBiAWDRpoWtPM+d40YoBL3q2NGGQuoJAh1D53krAPEfQz9T+izZb9seDAIaHehvzyNYYnWcozpOLUtMV8SoloQoGxwjStPAv+9tgtBHY9zTM9nzciw6wFSMMYkNAd9ERXRrO8y3DBpR+0Hqf35yRoENSjLDHuisUQRpCOecSUu98QqsIXpX3pSK15IsEQm0QWfz7AMrx/EJ5FpRQl5/bmog0bKfxulOiYsJ5fK7L2x773moXcYUWdZdLi0MtgZbCZwB6kEejCmBY6PIAe0sPflLGIIEFTiPvNTjQKSDr393FvoS3p3BBE3c4wU0VWIGe9mMuqcTx3vLAe99Y+zbylxFoHBfw+ePVXFApVDTXVSA/oAbNRnCHtFPbGFNVAMWsB8vU8+5m30SMAshLhH4nIrgqXPdO6jfmQJpERFWGjfyQ1NeTiY43HlsYJdy5SmfLS9qvR4e5Gb2zsg7ZwuswbWFnK+uaXwxo/2IX0e3fL9qZWdo09H1JaSngdKArlTCkV1JcNJrVyZAFXn8A2W4306+YX3op8U8MVk54saNZA/jVQGsIzUgx9T72R6n1GME=
