export default {
  themeColorLighten5: (state, getters) => `${getters.themeColorBase} lighten-5`,
  themeColorLighten4: (state, getters) => `${getters.themeColorBase} lighten-4`,
  themeColorLighten3: (state, getters) => `${getters.themeColorBase} lighten-3`,
  themeColorLighten2: (state, getters) => `${getters.themeColorBase} lighten-2`,
  themeColorLighten1: (state, getters) => `${getters.themeColorBase} lighten-1`,
  themeColor: state => state.themeColorBase,
  themeColorDarken1: (state, getters) => `${getters.themeColorBase} darken-1`,
  themeColorDarken2: (state, getters) => `${getters.themeColorBase} darken-2`,
  themeColorDarken3: (state, getters) => `${getters.themeColorBase} darken-3`,
  themeColorDarken4: (state, getters) => `${getters.themeColorBase} darken-4`,
  themeColorAccent1: (state, getters) => `${getters.themeColorBase} accent-1`,
  themeColorAccent2: (state, getters) => `${getters.themeColorBase} accent-2`,
  themeColorAccent3: (state, getters) => `${getters.themeColorBase} accent-3`,
  themeColorAccent4: (state, getters) => `${getters.themeColorBase} accent-4`,
};
